from setuptools import setup
from version import get_rt_env_version

env_name, env_ver = get_rt_env_version()
setup(
    name='env',
    version=env_ver,
    description=env_name,
    url='https://github.com/RT-Thread/env.git',
    author='RT-Thread Development Team',
    author_email='rt-thread@rt-thread.org',
    keywords='rt-thread',
    license='Apache License 2.0',
    project_urls={
        'Github repository': 'https:/github.com/rt-thread/env.git',
        'User guide': 'https:/github.com/rt-thread/env.git',
    },
    python_requires='>=3.11',
    install_requires=[
        'SCons>=4.0.0',
        'requests',
        'psutil',
        'tqdm',
        'kconfiglib',
        'anthropic>=0.39.0',
        'click>=8.1.7',
        'prompt_toolkit>=3.0.47',
        'rich>=13.7.1',
        'httpx>=0.27.0',
        'pydantic>=2.8.2',
        'pyyaml>=6.0.2',
        'windows-curses; platform_system=="Windows"',
    ],
    packages=[
        'env',
        'env.cmds',
        'env.cmds.cmd_package',
        'eagent',
        'eagent.commands',
        'eagent.context',
        'eagent.core',
        'eagent.files',
        'eagent.hooks',
        'eagent.mcp',
        'eagent.permissions',
        'eagent.prompt',
        'eagent.skills',
        'eagent.tools',
        'eagent.tui',
        'eagent.utils',
    ],
    package_dir={
        'env': '.',
        'env.cmds': 'cmds',
        'env.cmds.cmd_package': 'cmds/cmd_package',
        'eagent': 'eagent',
    },
    package_data={'': ['*.*']},
    exclude_package_data={'': ['MANIFEST.in']},
    include_package_data=True,
    entry_points={
        'console_scripts': [
            'rt-env=env.env:main',
            'menuconfig=env.env:menuconfig',
            'pkgs=env.env:pkgs',
            'sdk=env.env:sdk',
            'system=env.env:system',
            'agent=eagent.cli:main',
            'eagent=eagent.cli:main',
        ]
    },
)
